# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20170110_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos'),
        ),
    ]
