# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20170112_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='shoeID',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='data.Shoe'),
        ),
    ]
