# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_shoe_size_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size_in_cart',
        ),
    ]
